.github/workflows/ci.yaml
Signed-off-by: parauliya <aman@infracloud.io>
GitHub Action is not working as expected because there were few errors in the way things works with Docker Action v2
=> Fixed Image Tags

.github/workflows/ci.yaml
Adds the master branch github actions to pbnj.next
Fixes: #
I have:
=> Eng 9717 ci setup

.dockerignore, Dockerfile, Makefile, README.md, cmd/server.go, scripts/etc-passwd
Add Dockerfile. Add port option for server subcommand. Updated Readme.
Fixes: #
Yes, manually. I ran `make image` and `make run-image` and then manually hit the API to test.
no, net new.
I have:
=> Eng 9460 dockerfile

pkg/oob/oob.go, pkg/repository/repo.go, pkg/task/task.go, server/grpcsvr/oob/bmc/bmc.go, server/grpcsvr/oob/machine/machine.go, server/grpcsvr/oob/machine/machine_test.go, server/grpcsvr/rpc/bmc.go, server/grpcsvr/rpc/machine.go, server/grpcsvr/rpc/task.go, server/grpcsvr/rpc/task_test.go, server/grpcsvr/taskrunner/taskrunner.go, server/grpcsvr/taskrunner/taskrunner_test.go
Update error handling. update repository.Error to implement the error
interface for better error handling interactions.
This is a start to improving error handling through out the service.
Fixes: #
I have:
=> Update error handling

go.mod, pkg/oob/oob.go, pkg/oob/oob_test.go, server/grpcsvr/oob/bmc/bmc.go, server/grpcsvr/oob/bmc/reset_bmclib.go, server/grpcsvr/oob/bmc/users_bmclib.go, server/grpcsvr/oob/common.go, server/grpcsvr/oob/common_test.go, server/grpcsvr/oob/machine/machine.go, server/grpcsvr/oob/machine/machine_bootdevice_ipmi.go, server/grpcsvr/oob/machine/machine_bootdevice_ipmi_test.go, server/grpcsvr/oob/machine/machine_power_bmclib.go, server/grpcsvr/oob/machine/machine_power_ipmi.go, server/grpcsvr/oob/machine/machine_power_redfish.go, server/grpcsvr/oob/machine/machine_test.go, server/grpcsvr/rpc/bmc.go, server/grpcsvr/rpc/machine.go, server/grpcsvr/taskrunner/taskrunner.go
Add BMC cold reset functionality. Make implementing
new drivers a little easier. Manually tested successfully. 
Fixes: #
I have:
=> Add BMC cold reset

.github/workflows/ci.yaml
For testing purposes, we need a built container image. The intent of this is to remove it before this merges to master.
Fixes: #
I have:
=> Make container images for pbnj.next branch

.github/workflows/ci.yaml
Update github actions to login to quay.io for pbnj.next branch
Fixes: #
I have:
=> Update github actions to login to quay.io for pbnj.next branch

server/grpcsvr/rpc/bmc_test.go
Add basic BMC endpoint tests
Fixes: #
I have:
=> Add basic BMC endpoint tests

go.mod, go.sum, pkg/oob/oob.go, pkg/oob/oob_test.go, server/grpcsvr/oob/bmc/bmc.go, server/grpcsvr/oob/bmc/users_bmclib.go, server/grpcsvr/oob/machine/machine.go, server/grpcsvr/oob/machine/machine_power_bmclib.go, server/grpcsvr/oob/machine/machine_power_redfish.go, server/grpcsvr/rpc/bmc_test.go, server/grpcsvr/server_test.go
numerous bugfixes for timeouts issues and nil pointer exceptions.
Fixes: #
I have:
=> Bugfix timeouts nil pointer exception

pkg/zaplog/middleware.go
Calls to the task.Status endpoint panic as they don't contain any Authn fields. This fixes that by recovering and just moving on.
Fixes: #
I have:
=> Fix panic in UnaryLogBMCIP

CONTRIBUTING.md, README.md, docs/Authorization.md, docs/CODE_STRUCTURE.md, docs/DCO.md
Help lower the barrier to entry and increase the maintainability of PBnJ with a contributors guide and some associated documentation.
rendered doc here: 
https://github.com/tinkerbell/pbnj/blob/70928f48827abd2da9354122e5c1f89466aef18f/CONTRIBUTING.md
Fixes: #
I have:
=> Add contributors guide:

cmd/pbnj/server.go
Helps for measuring latency.
see: https://github.com/grpc-ecosystem/go-grpc-prometheus#histograms
Fixes: #
I have:
=> Enable metrics time histograms:

server/grpcsvr/rpc/task.go
clean up TaskService Status rpc
Fixes: #
I have:
=> clean up TaskService Status rpc

server/grpcsvr/oob/machine/machine_power_redfish.go
For the redfish power setting we need to check power status before attempting a cycle.
If the machine is off return error.
The gofish library will return non-error if a machine is off and a `redfish.ForceRestartResetType` is requested.
This keeps this implementation in line with the others, including ipmitool.
Fixes: #
I have:
=> Update redfish power cycle:

README.md
Add the website to README.md
Linking to the website is a good idea.
#52 needed to be rebased and the change is so trivial I figured I would rebase it on @mrmrcoleman's behalf
Fixes: #52
=> Add website to README.md

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Update all refs from master -> main
=> Prepare for default branch rename

Dockerfile
New ipmitool has ciphersuite 17 support.
I have:
=> Update ipmitool commit in Dockerfile to latest.

Dockerfile
There are issues on some hardwares with new ipmitool.
Signed-off-by: Raj-Dharwadkar <rdharwadkar@equinix.com>
Fixes: #
I have:
=> Revert change made to ipmitool.

Makefile
Signed-off-by: Micah Hausler <mhausler@amazon.com>
Enable verbose `make help` output and re-arrange some targets. This uses the help formatting from [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/blob/028566615757f423b09872b18bab189a65de2b3d/testdata/project-v2/Makefile#L30-L32) 
Before
```
$ make help
buf-lint                       run linting
build                          compile the binary for the native OS
cover                          Run unit tests with coverage report
darwin                         complie for darwin
evans                          run evans grpc client
goimports-ci                   run goimports for ci
goimports                      run goimports
image                          make the Container Image
linux                          complie for …
```
=> Add verbose make help

Makefile, grpc/oob/bmc/bmc.go, grpc/oob/common_test.go, grpc/rpc/bmc_test.go, grpc/taskrunner/taskrunner.go, test/runner/common.go
The version of golangci-lint was causing issues. It was also a bit old. Updating resolves the issues.
Fixes: #
I have:
=> Fix linting errors:

Dockerfile
The new version include bug fixes that address issues present in the previous release, leading to a more stable and reliable tool
https://github.com/ipmitool/ipmitool/blob/master/ChangeLog
It is going to update the ipmitool
https://github.com/ipmitool/ipmitool/issues/163
Fixes: #
I compiled the code in a Docker container and ran it against physical hardware. 
It fixes bugs, no additional changes are required.
I have:
=> Update ipmitool commit in Dockerfile to 1.8.19
