- drivers/racadm/shell.go
This change removes the fake keyboard-interactive function and handles
keyboard-interactive properly.
Dell removed the old password authentication method for ssh logins,
and now require either an ssh key or keyboard-interactive logins.
> support keyboard-interactive password authentication

- drivers/ipmitool/bmc.go
- drivers/ipmitool/boot.go
- drivers/ipmitool/options.go
- drivers/ipmitool/power.go
- drivers/ipmitool/shell_test.go
- interfaces/bmc/bmc.go
- interfaces/bmc/http.go
- interfaces/boot/boot.go
- interfaces/boot/http.go
- interfaces/power/http.go
- interfaces/power/power.go
This change allows for a specific cipher to
be defined by default, as well as adds an api header to allow the
cipher to be defined at a per request level to support older hardware.
some older bmc models don't have support for newer ciphers that are
supported by ipmitool.
> add configurable cipher

- .github/workflows/ci.yaml
Signed-off-by: parauliya <aman@infracloud.io>
GitHub Action environment variables gets passed to PR only if they
starts from a branch that is local, so fork does not get a QUAY PASSOWRD
and USERNAME, this is to avoid security issue.
We should push images to Quay only if the commit is in master.
> Login to quay should only work if commit is in master

- .github/workflows/ci.yaml
Fix golangci-lint GitHub actions error. I've tried to reproduce this error locally with [act](https://github.com/nektos/act) but I'm not able to. Testing now directly with GitHub.  Upgrading to golangci-lint v2 and reordering it to run first. Root cause seems to be here: https://github.com/golangci/golangci-lint-action/issues/23#issuecomment-647177770 
```bash
Error: /bin/tar: ../../../go/pkg/mod/goa.design/goa@v2.2.4+incompatible/http/mux.go: Cannot open: File exists
.
.
.
Error: /bin/tar: ../../../go/pkg/mod/golang.org/x/text@v0.3.4/width/runes_test.go: Cannot open: File exists
```
in order to get clean GitHub action runs
Fixes: #
I have:
> github actions golangci-lint fix

- .gitignore
- examples/clients/ruby/lib/pbnj/client.rb
- examples/clients/ruby/lib/pbnj/errors.rb
- examples/clients/ruby/lib/pbnj/task.rb
Add a small ruby library to show how to get a power status from PBnJ.
Run the example code with `make ruby-client-demo host=10.10.10.10 user=ADMIN pass=ADMIN`
Fixes: #
I have:
> Update ruby client example

- Dockerfile
- cmd/pbnj/server.go
- pkg/healthcheck/healthcheck.go
- pkg/http/handlers.go
- pkg/http/http.go
- server/grpcsvr/server.go
- server/grpcsvr/server_test.go
- server/grpcsvr/taskrunner/taskrunner.go
healthcheck endpoint includes number of running tasks and total tasks executed.
In addition to the healthcheck endpoint, `/_/ready` and `/_/live` have also been
implemented for readiness and liveness probes to hit. Currently they always
return a 200 status. In the future we may be able to make the more useful.
> add healthcheck endpoint

- .github/workflows/ci.yaml
Create container images on pbnj.next but dont update latest image tag
Fixes: #
I have:
> Create container images on pbnj.next but dont update latest image tag

- server/grpcsvr/rpc/bmc.go
The current 5-minute timeout creates an undesired user experience as the user has to wait up to 5 minutes for a task to finish
and the task status to be updated as complete. Changing the timeout to maybe lower than it should be but this will improve the user experience, for now.
Fixes: #
I have:
> Decrease BMC actions timeout

- .github/workflows/ci.yaml
- README.md
These drone CI banners are no longer used
> Replace Drone badge with GitHub Action

- cmd/pbnj/server.go
- pkg/zaplog/middleware.go
Add the BMC IP to all logs in order to provide better search/grouping in the logs for requests.
Fixes: #
I have:
> Add bmc ip to all log lines

- server/grpcsvr/rpc/bmc.go
- server/grpcsvr/rpc/machine.go
The request validation is using middleware and the explicit calls to Validate in each RPC is not needed.
Fixes: #
I have:
> Remove unneeded validation call in rpc code:

- Dockerfile
Use the 1.18 release version of `ipmitool`. Fixes some "no matching cipher suite" issues.
Fixes: #
I have:
> Use release version of ipmitool:

- cmd/server.go
Viper library has a bug where dashes in an
env var just dont work. https://github.com/spf13/viper/issues/1019
Changing metric port setting to not use dashes.
Fixes: #
I have:
> Fix viper cant handle dashes:

- server/grpcsvr/rpc/task.go
- server/grpcsvr/rpc/task_test.go
Not returning an actual gRPC error causes the log line thats returned for each call to an RPC to be of error level and contain a stacktrace. Using an actual gRPC error in the return keeps the log level at info and just returns the contents of the error. Better user experience when searching and filtering logs.
Before:
```
{
"level": "error",
"ts": 1615309334.3296337,
"caller": "zap/options.go:203",
"msg": "finished unary call with code Unknown",
"service": "github.com/tinkerbell/pbnj",
"grpc.start_time": "2021-03-09T17:02:14Z",
"system": "grpc",
"span.kind": "server",
"grpc.service": "github.com.tinkerbell.pbnj.api.v1.Task",
"grpc.method": "Status",
"peer.address": "192.168.0.195:48462",
"requestID": "c5da62f4f8acc7c1e3423e793d127eee",
"error": "record id not found: JUSTTESTING", …
```
> Update gRPC error 

- .github/workflows/ci.yaml
- server/grpcsvr/oob/machine/machine.go
the previous http version of pbnj defined a power-cycle to do the following:
1. if a machine is currently powered on, power it off
and then power it on again.
OR
2. if a machine is currently powered off, power it on
This definition does not reflect how any other BMC tool in the industry defines power-cycle.
This definition is used by equinix metal pbnj clients and these same clients did not change their definition when migrating to pbnj.next :(
This change is being created in a branch of its own that should NEVER be merged to master/main.
Fixes: #
I have:
> Create equinix metal specific functionality:

- pkg/oob/oob.go
- server/grpcsvr/oob/machine/machine.go
`ipmitool chassis power reset` against a powered off machine will apparently return successful but do nothing.
Switching to checking status and then acting.
Fixes: #
I have:
> Move to different logic for power-cycle:

- .github/workflows/ci.yaml
- cmd/server.go
- server/grpcsvr/rpc/bmc.go
- server/grpcsvr/rpc/machine.go
- server/grpcsvr/server.go
This allows end-users to increase or decrease the timeout at runtime.
BMCs can be unpredictable, being able to tune the timeout of BMC calls is very helpful.
Fixes: #
I have:
> Add configurable timeout for BMC calls

- server/grpcsvr/rpc/task.go
Keying the gRPC error off the code is problematic because not all BMC calls return a code.
All BMC calls that do fail will have a message so we use that.
Fixes: #
I have:
> Key gRPC error off record.Error.Message:

- go.sum
- grpc/oob/machine/machine.go
This adds the metadata from bmclib into the OTEL spans so that we can understand if certain failures are related to a specific bmclib provider.
It also fixes one instance where a span wasn't correctly labeled as an error.
- go test ./...
- CI ?
- Manually running a local instance configured to emit traces
N/A
I have:
> Add bmclib client metadata to to OTEL spans

- grpc/oob/machine/machine.go
- grpc/rpc/machine.go
This puts the error message from e.g. ipmitool into the trace right when the command runs.
It also passes along RPC context into the Task so that we know which RPC triggered a Task.
This eases debugging of bmclib failures in the span where the command was run.
- I ran an updated container and confirmed that the improved error message showed up in Jaeger
- The parent-child relationship also now exists.
N/A
I have:
> Add the error message to the client.PowerSet trace

- grpc/oob/machine/machine.go
This fixes power cycle requests. At line [307](https://github.com/tinkerbell/pbnj/blob/1ffd6a4ffbf4c8341e05cea09c4440537099e32a/grpc/oob/machine/machine.go#L307) If `action == v1.PowerAction_POWER_ACTION_CYCLE.String()` then we set the requested power state to be  the string `"POWER_ACTION_ON"`. This causes the `client.SetPowerState(ctx, pwrAction)` to fail as the string `"POWER_ACTION_ON"` is not recognized by bmclib. We need to pass `"on"` as is done in line [219](https://github.com/tinkerbell/pbnj/blob/1ffd6a4ffbf4c8341e05cea09c4440537099e32a/grpc/oob/machine/machine.go#L219).
Fixes: #
Tested manually against `vaporio/ipmi-simulator` container image.
I have:
> Fix power on string in cycle check:

- grpc/rpc/bmc.go
- grpc/rpc/machine.go
This PR follows f8c0e55 and wires up the rest of our RPC calls to their handlers
This further improves our otel tracing visibility
- light testing with evans
N/A
I have:
> Pass all RPC span contexts to handlers

- grpc/oob/machine/machine.go
honeycomb.io doesn't currently support rendering StringSlice attributes.
We'll switch to using strings for now, with the hope that this can some day be reverted.
honeycomb.io doesn't currently support StringSlice attributes.
- Build and test with evans
N/A
I have:
> convert StringSlice attributes to Strings for now

- grpc/rpc/bmc.go
- grpc/rpc/machine.go
Not calling cancel is not ideal. It was previously thought that a defer in this context would be called before the function was run. This is not the case.
Fixes: #
I have:
> Defer the cancel in RPC background tasks:

- cmd/server.go
- go.mod
- go.sum
github.com/dgrijalva/jwt-go -> github.com/golang-jwt/jwt/v4
because of CVE-2020-26160. See: https://github.com/advisories/GHSA-w73w-5m7g-f7qc
fixes security advisory. See https://github.com/tinkerbell/pbnj/security/dependabot/go.sum/github.com%2Fdgrijalva%2Fjwt-go/open 
Fixes: #
Manually tested using `make run-server` and `make evans`. Followed https://github.com/tinkerbell/pbnj/blob/main/docs/Authorization.md to test auth.
I have:
> Migrate to newer/more maintained jwt library:

- grpc/oob/bmc/bmc.go
- grpc/oob/machine/machine.go
Ipmitool is the older of the two protocols between itself and Redfish. Many machines would benefit and possibly be more reliable if Redfish was tried first.
Fixes: #
I have:
> Try Redfish first when communicating with a BMC:

- grpc/oob/machine/machine.go
Dear reader, the world has changed.
https://github.com/honeycombio/husky/pull/17 has been merged.
Reverts #109 / 3581292 as the underlying issue has been fixed for honeycomb.
I have:
> Revert "convert StringSlice attributes to Strings for now"

- grpc/oob/bmc/bmc.go
- grpc/oob/machine/machine.go
This reverts commit 32e7bbd9774f598c9e86b6729fca30b10bd18ee2.
Some redfish implementations are buggy and while being compatible
they incorrectly report their power status (ASRRs E3C246D4I-NL)
until we're a bit more confident that various redfish implementation
behave as expected lets go with IPMI being attempted first.
https://github.com/bmc-toolbox/bmclib/blob/master/client.go#L104
If theres a pressing need to have redfish attempted first
the change can be pushed down into bmclib to ignore redfish on the ASRRs
although this does not seem like an ideal solution at the moment.
Fixes: #
This should have no negative impact on existing users.
I have:
> Revert "Try Redfish first when communicating with a BMC:"

- Dockerfile
- grpc/oob/bmc/bmc.go
- grpc/rpc/bmc.go
Create client.Thing spans in bmc.go functions that do the heavy lifting.
Fixes: #122 
If you're sending otel spans, now you'll send more.
I have:
> Add additional OTEL tracing into grpc/oob/bmc/bmc.go

- Dockerfile
Its silly that we missed this in the original PR incrementing the ipmitool version, but here we go.
ipmitool fails to start up with the error `ipmitool init error Failed to initialize the OEM info dictionary`,
this pulls in the fix referenced in the linked issue.
https://github.com/ipmitool/ipmitool/issues/377
Fixes: #
- Tested locally and on a few machines
No impact.
I have:
> Fixes ipmitool init error Failed to initialize the OEM info dictionary

- .github/workflows/ci.yaml
They were all very old. CI is failing because of the upload-artifact version.
Fixes: #
I have:
> Update all CI action images:

- .github/workflows/ci.yaml
- .golangci.yml
- Dockerfile
- Makefile
- cmd/machine.go
- cmd/nmi.go
- cmd/root.go
- cmd/screenshot.go
- cmd/sel.go
- cmd/server.go
- go.mod
- grpc/oob/common_test.go
- grpc/rpc/task_test.go
- grpc/server_test.go
- grpc/taskrunner/taskrunner_test.go
- pkg/logging/logging.go
- test/main.go
- test/runner/runner.go
Needed for security dependency updates.
Fixes: #
I have:
> Update Go to 1.23:
